version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long from different repositories
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    # GitHub actions are using git tags (v1 = v1.2 = v1.2.3) which should be compatible until a major change is performed
    update-types: 
    - "version-update:semver-minor"
    - "version-update:semver-patch"
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long from different repositories
    time: "00:00"
  open-pull-requests-limit: 10
