language: android
jdk:
    - oraclejdk8
android:
  components:
    # The BuildTools version used by NewPipe
    - tools
    - build-tools-29.0.3

    # The SDK version used to compile NewPipe
    - android-29

before_install: 
  - yes | sdkmanager "platforms;android-29"
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest

licenses:
  - '.+'
