blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ IRC
    url: https://web.libera.chat/#newpipe
    about: Chat with us via IRC for quick Q/A
  - name: ðŸ’¬ Matrix
    url: https://matrix.to/#/#newpipe:libera.chat
    about: Chat with us via Matrix for quick Q/A
