blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://github.com/TeamNewPipe/NewPipe/discussions/new?category=questions
    about: Ask about anything NewPipe-related
  - name: ğŸ’¬ IRC
    url: https://web.libera.chat/#newpipe
    about: Chat with us via IRC for quick Q/A
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#newpipe:libera.chat
    about: Chat with us via Matrix for quick Q/A
