name: Build Pull Requests

on:
  pull_request:
    branches: # we might want to add all branches here
      - 'master'
      - 'dev'

jobs:
  build:
    name: Build project & generate APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 1.8

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk

      - name: Create comment linking to the artifact
        uses: thollander/actions-comment-pull-request@1f25fabed60c3f141743c3a522529950a8fb2191
        with:
          message: 'The APK was build successfuly. You can find it there: https://github.com/TobiGr/NewPipe/actions/runs/${{github.run_id}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
